#=============================================================================
#
#  File: SConstruct
#
#  Author: bing
#
#  Date: 2016-09-01
#
#  Version: v2.0
#
#  Github/Mail: https://github.com/binchen-china    <563853086@qq.com>
#
#  Note: build project file
#
#=============================================================================

env = Environment()

TARGETNAME = 'DMFramework'

FILELIST = Split('main.cpp DMServer.cpp DMMultiProcess.cpp DMMemoryPool.cpp DMLogManager.cpp DMJsonConfig.cpp DMServerImpl.cpp DMDispatcher.cpp DMAcceptor.cpp DMMessageQueue.cpp DMMessageEvent.cpp DMServiceMap.cpp DMSessionManager.cpp DMMessageParser.cpp') 

HEADFILEPATH = Split('../../3rd ../../3rd/amqpcpp ../../3rd/mysqlpp/lib ../../3rd/mysql-connector-c/include ../RabbitMQ ../Redis ../MySQL')

LIB = Split('ACE pthread jsoncpp amqpcpp')

FLAGS = Split('-std=c++11 -Wall')

TARGETFILE = Program(target = TARGETNAME,source = FILELIST,CPPPATH = HEADFILEPATH,LIBS = LIB,CCFLAGS = FLAGS)

#install
INSTALL = env.Install('../Lib', TARGETFILE)
env.Alias('install',INSTALL)
