env = Environment()

TARGETNAME = 'DMRedis'

FILELIST = Glob('*.cpp') 

HEADFILEPATH = Split('../../3rd ../../3rd/amqpcpp')

FLAGS = Split('-std=c++11 -Wall')

TARGETFILE = StaticLibrary(target = TARGETNAME,source = FILELIST,CPPPATH = HEADFILEPATH,CCFLAGS = FLAGS)

#install
INSTALL = env.Install('../Lib', TARGETFILE)
env.Alias('install',INSTALL)
